### PR TITLE
add gatsby v3 and update peerDependencies 🚑

### PR DESCRIPTION
**Pull request by TheeMattOliver**
# Description

`gatsby-plugin-intl` won't work with Gatsby V3 bc it has out of date peer dependencies.

Updating to Gatsby V3 should be pretty easy, hopefully, and just be a matter of updating the peer deps in the package repo.

[Gatsby3.0 Migration docs](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3#updating-community-plugins)

[Updating dependencies
](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3#updating-your-dependencies
)

Please update peer deps and let us know what else we can do to help. 👍

Fixes # (issue)

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: gatsby@3.0.3
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"3.0.3" from the root project
npm ERR!   peer gatsby@"^3.0.0-next.0" from gatsby-plugin-manifest@3.0.0
npm ERR!   node_modules/gatsby-plugin-manifest
npm ERR!     gatsby-plugin-manifest@"3.0.0" from the root project
npm ERR!   9 more (gatsby-plugin-offline, gatsby-plugin-react-helmet, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^2.0.0" from gatsby-plugin-intl@0.3.3
npm ERR! node_modules/gatsby-plugin-intl
npm ERR!   gatsby-plugin-intl@"^0.3.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

## Type of change

Please delete options that are not relevant.

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by AleC77** [comment]
any update?

**Comment by admkopec** [comment]
@TheeMattOliver, I believe you might have a bug in your fix, as now the `package.json` file has two entries for **peerDependencies** (one at line 26 – added by you, and one at line 41) The latter still points to `"gatsby": "^2.0.0"`, and unfortunately that version appears to be required by npm (v7.5.4). You should remove the second entry and update this pull request, as that should fix the error thrown by npm. I have checked it at my [fork](https://github.com/admkopec/gatsby-plugin-intl) and it appears to  be working properly.

**Review by admkopec — APPROVED** [review]

**Review by whyboris — APPROVED** [review]
Please merge 🙇

**Comment by whyboris** [comment]
@wiziple -- this seems like a great improvement to your excellent plugin 😊 

I've even tested against _Gatsby 5_ and your plugin still works 🚀 

Would you be willing to merge a PR for _Gatsby 5_ if I create one?

**Pull request merged**
